package client;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author jack1
 */
public class Login extends javax.swing.JFrame {
    
    public final String quote = "'";
    private int passwordClick = 0;
    private int count = 0;
    private int maxAttemps = 3;
    List<String> users = new ArrayList<>();
    private commonInterface chat;
    
    public Login(commonInterface chat) {
        this.setVisible(true);
        this.chat = chat;
        initComponents();
        initFrame();
    }
    
    public void initFrame() {
        this.setDefaultCloseOperation(this.EXIT_ON_CLOSE);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        int height = 500;
        int width = 1000;
        this.setSize(width, height);
        this.setTitle("Online ChatRoom");      
    }
    
    public JPanel getPanel() {
        return this.loginPanel;
    }
    
    public void goToApplyForNewMember() {
        JPanel newMember = new ApplyForNewMember(this);
        this.getContentPane().removeAll();
        this.add(newMember);
        this.revalidate();
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginPanel = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        loginButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        passwordText = new javax.swing.JPasswordField();
        showPasswordButton = new javax.swing.JButton();
        applyButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        loginPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nameLabel.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(255, 255, 255));
        nameLabel.setText("UserName:");
        loginPanel.add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, -1, -1));

        passwordLabel.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(255, 255, 255));
        passwordLabel.setText("Password:");
        loginPanel.add(passwordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 139, -1));

        nameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextActionPerformed(evt);
            }
        });
        loginPanel.add(nameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 170, 33));

        loginButton.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        loginPanel.add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 310, 74, -1));

        resetButton.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });
        loginPanel.add(resetButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 310, 76, -1));

        passwordText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordTextActionPerformed(evt);
            }
        });
        loginPanel.add(passwordText, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 250, 170, 30));

        showPasswordButton.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        showPasswordButton.setText("Show password");
        showPasswordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPasswordButtonActionPerformed(evt);
            }
        });
        loginPanel.add(showPasswordButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 250, 140, 30));

        applyButton.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        applyButton.setText("Apply for membership");
        applyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyButtonActionPerformed(evt);
            }
        });
        loginPanel.add(applyButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 310, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/source/mainbackground.png"))); // NOI18N
        loginPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, -1));

        getContentPane().add(loginPanel, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        nameText.setText("");
        passwordText.setText("");
    }//GEN-LAST:event_resetButtonActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed

        //get encryped password
        passwordText.setEchoChar('*');
        String password = new String(passwordText.getPassword());

        //Check if username and password combination is in the database
        String query = "SELECT * FROM UserData WHERE Username=" + quote + nameText.getText() + quote + " AND Password="
                + quote + password + quote;
        database.DBOperations db = new database.DBOperations();
        db.createConnection();
        db.createTable();
        
        try {

            //If the username and password combination in the database, you can login
            if (db.selectQuery(query).next()) {
                JOptionPane.showMessageDialog(null, "Congrats", "You have successfully loggin!", JOptionPane.INFORMATION_MESSAGE);
                
                chat.sendCurrentUserName(nameText.getText());
                new ClientImplGui(chat, nameText.getText());
                
            } //If not in the database
            else {
                
                JOptionPane.showMessageDialog(null, "The combination of username and password is wrong\nOr you have not registered", "Warning!", JOptionPane.ERROR_MESSAGE);

                //Warning, if exceeds attemps redirect to apply for new member page
                count++;

                //have not reached maxium attemps,;
                if (count > maxAttemps) {
                    JOptionPane.showMessageDialog(null, "Sorry, you have exceeded maximum attemps, please apply for new memberhsip", "Warning!", JOptionPane.ERROR_MESSAGE);
                    goToApplyForNewMember();
                }                
                
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        

    }//GEN-LAST:event_loginButtonActionPerformed

    private void passwordTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordTextActionPerformed

    private void showPasswordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPasswordButtonActionPerformed
        
        passwordClick++;
        passwordText.setEchoChar((char) 0);
        
        if (passwordClick % 2 == 0) {
            passwordText.setEchoChar('*');
        }
        

    }//GEN-LAST:event_showPasswordButtonActionPerformed

    private void applyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyButtonActionPerformed
        goToApplyForNewMember();

    }//GEN-LAST:event_applyButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton applyButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton loginButton;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameText;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPasswordField passwordText;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton showPasswordButton;
    // End of variables declaration//GEN-END:variables
}
